# Generated by Django 5.2.17 on 2026-09-03 15:03

import credenciamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljornalista',
            name='dados_profissionais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfiljornalista',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=credenciamento.models.caminho_documento),
        ),
        migrations.AddField(
            model_name='perfiljornalista',
            name='mini_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitacaocredenciamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
