# Generated by Django 5.2.17 on 2026-09-26 00:45

import credenciamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciamento', '0002_perfiljornalista_dados_profissionais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiljornalista',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=credenciamento.models.caminho_foto_perfil),
        ),
        migrations.AlterField(
            model_name='solicitacaocredenciamento',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=credenciamento.models.caminho_foto_solicitacao),
        ),
    ]
