# Generated by Django 5.2.17 on 2026-09-04 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['teste', 'ativa', 'pagamento_pendente'])), fields=('user',), name='assinatura_uma_em_andamento_por_usuario'),
        ),
    ]
