# Generated by Django 5.2.17 on 2026-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriomonitoramento',
            name='ultimo_alerta_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
