# Generated by Django 5.2.17 on 2026-09-02 00:46

import django.utils.timezone
import identidade.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('papel', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('admin', 'Admin')], default='free', max_length=20)),
                ('email_verificado', models.BooleanField(default=False)),
                ('interesses', models.JSONField(blank=True, default=list)),
                ('localidade', models.CharField(blank=True, max_length=150)),
                ('canal_preferido', models.CharField(blank=True, choices=[('email', 'E-mail'), ('push', 'Push')], max_length=20)),
                ('onboarding_concluido', models.BooleanField(default=False)),
                ('onboarding_pulado', models.BooleanField(default=False)),
                ('onboarding_atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('consentimento_aceito_em', models.DateTimeField(blank=True, null=True)),
                ('consentimento_versao_termos', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', identidade.managers.UserManager()),
            ],
        ),
    ]
