# Generated by Django 5.2.17 on 2026-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferencias_cookies',
            field=models.JSONField(blank=True, default=dict, help_text="Ex.: {'analytics': false, 'personalizacao': false}. Chave 'essenciais' nunca é armazenada aqui (sempre ativa)."),
        ),
        migrations.AddField(
            model_name='user',
            name='preferencias_cookies_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
