# Generated by Django 5.2.17 on 2026-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0002_user_preferencias_cookies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deve_trocar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
