# Generated by Django 5.2.17 on 2026-09-03 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_noticias', '0002_newsitem_localidade'),
        ('comunidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comentario',
            name='comentario_exatamente_um_alvo',
        ),
        migrations.AddConstraint(
            model_name='comentario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('news_item__isnull', True), ('publicacao__isnull', False)), models.Q(('news_item__isnull', False), ('publicacao__isnull', True)), _connector='OR'), name='comentario_exatamente_um_alvo'),
        ),
    ]
