# Generated by Django 5.2.17 on 2026-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0002_remove_comentario_comentario_exatamente_um_alvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='ocultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='ocultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
