# Generated by Django 5.2.17 on 2026-09-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_acontecimento', models.CharField(max_length=300)),
                ('categoria_dominante', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cluster de noticias',
                'verbose_name_plural': 'clusters de noticias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroExecucaoIngestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('itens_por_fonte', models.JSONField(default=dict, help_text="Ex.: {'G1': 12, 'UOL': 9}")),
                ('erros_por_fonte', models.JSONField(blank=True, default=dict, help_text='Fontes que falharam nesta execucao e a mensagem de erro registrada.')),
                ('total_itens_ingeridos', models.PositiveIntegerField(default=0)),
                ('total_grupos_formados', models.PositiveIntegerField(default=0)),
                ('total_duplicatas_agrupadas', models.PositiveIntegerField(default=0, help_text='total_itens_ingeridos - total_grupos_formados')),
                ('chamadas_summarization_provider', models.PositiveIntegerField(default=0)),
                ('tokens_utilizados_summarization', models.PositiveIntegerField(blank=True, null=True)),
                ('custo_estimado_summarization_usd', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'registro de execucao de ingestao',
                'verbose_name_plural': 'registros de execucao de ingestao',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumo_proprio', models.TextField(blank=True, help_text='Conteudo proprio gerado pelo SummarizationProvider — NUNCA copia do texto bruto original.')),
                ('conteudo_bruto', models.TextField(blank=True, help_text='Conteudo bruto ingerido da fonte (snippet/summary do RSS), guardado apenas para auditoria/depuracao interna — nunca deve ser exibido como resumo_proprio (implementation-contract.md, criterio de aceite 4).')),
                ('url_fonte_original', models.URLField(max_length=1000, unique=True)),
                ('nome_fonte', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('timestamp_publicacao_fonte', models.DateTimeField(blank=True, null=True)),
                ('timestamp_ingestao', models.DateTimeField(auto_now_add=True)),
                ('urgente', models.BooleanField(default=False)),
                ('status_revisao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('nao_aplicavel', 'Nao aplicavel (nao exige revisao)')], default='pendente', max_length=20)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='catalogo_noticias.newscluster')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-timestamp_ingestao'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('url_fonte_original', ''), _negated=True), models.Q(('nome_fonte', ''), _negated=True)), name='newsitem_fonte_obrigatoria')],
            },
        ),
    ]
