# Generated by Django 5.2.17 on 2026-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_noticias', '0002_newsitem_localidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_minutos', models.PositiveIntegerField(default=15)),
                ('ativo', models.BooleanField(default=True)),
                ('categorias_sensiveis', models.CharField(default='política,economia,segurança pública', max_length=500)),
                ('limiar_fontes_alta_relevancia', models.PositiveIntegerField(default=3)),
                ('dedup_limiar_similaridade', models.FloatField(default=0.55)),
                ('dedup_janela_horas', models.FloatField(default=24)),
                ('dedup_max_itens', models.PositiveIntegerField(default=300)),
                ('resumo_similaridade_maxima', models.FloatField(default=0.6)),
                ('resumo_trecho_copiado_maximo', models.FloatField(default=0.6)),
                ('dedup_cluster_sempre_exige_revisao', models.BooleanField(default=True)),
                ('llm_model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('llm_api_base_url', models.URLField(default='https://api.openai.com/v1', max_length=500)),
                ('llm_tamanho_lote', models.PositiveIntegerField(default=10)),
                ('llm_max_tokens_por_item', models.PositiveIntegerField(default=220)),
                ('llm_teto_gasto_diario_usd', models.FloatField(default=5.0)),
                ('llm_preco_por_1k_tokens', models.FloatField(default=0.15)),
                ('llm_timeout_segundos', models.PositiveIntegerField(default=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao de robo',
                'verbose_name_plural': 'configuracao de robos',
            },
        ),
        migrations.CreateModel(
            name='FonteRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria_padrao', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fonte de robo',
                'verbose_name_plural': 'fontes de robos',
                'ordering': ['nome'],
            },
        ),
    ]
