# Generated by Django 5.2.17 on 2026-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_noticias', '0004_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='conteudo_completo',
            field=models.TextField(blank=True, help_text='Texto integral da matéria extraído do RSS (content:encoded quando disponível, senão o summary), limpo de HTML. Exibido SEMPRE de forma truncada no frontend, com crédito + link para a fonte original (BRD secao 18) — nunca como conteúdo próprio.'),
        ),
    ]
