# Generated by Django 5.2.17 on 2026-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_noticias', '0006_newsitem_autoria_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonterobo',
            name='estado_padrao',
            field=models.CharField(blank=True, help_text="Sigla da UF coberta pela fonte (ex.: GO, SP). Alimenta 'Perto de Você'/Radar: itens ingeridos desta fonte herdam o estado quando o RSS não informa localidade. Vazio = nacional/sem recorte.", max_length=2),
        ),
    ]
