# Generated by Django 5.2.17 on 2026-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_noticias', '0009_newscluster_numero_fontes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['status_revisao', '-timestamp_ingestao'], name='feed_status_ingestao'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['categoria'], name='newsitem_categoria'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['urgente'], name='newsitem_urgente'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['pais', 'estado', 'cidade'], name='newsitem_localidade'),
        ),
    ]
