# Generated by Django 5.2.17 on 2026-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaonewsletter',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('noite', 'Noite')], default='manha', max_length=10),
        ),
    ]
