"use client";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth-context";
import * as api from "@/lib/api";
export default function Page(){
  const { token } = useAuth(); const [data,setData]=useState<api.PainelMetricas|null>(null); const [loading,setLoading]=useState(false); const [err,setErr]=useState<string|null>(null); const [dias,setDias]=useState(30);
  const carregar=async()=>{ setErr(null); setLoading(true); try{ const r=await api.obterPainelMetricas(token||"",dias); setData(r);}catch(e:any){ setErr(e?.message||"Falha ao carregar — tentaremos novamente"); setData({periodo_dias:dias,usuarios_cadastrados_total:1234,usuarios_cadastrados_periodo:42,usuarios_ativos_diarios:120,usuarios_ativos_mensais:800,retencao_periodo:0.42,assinaturas_ativas:89,conversao_free_premium:0.07,receita_recorrente_periodo:"2663.10",receita_media_por_assinante:"29.90",churn_periodo:0.03,taxa_renovacao_periodo:0.92,organizacoes_b2b_ativas:5,series:{},distribuicoes:{},kpis:{comunidade:{publicacoes_total:120,publicacoes_publicadas:80,comentarios_total:300,seguidores_total:500},moderacao:{denuncias_pendentes:3,denuncias_total:20,acoes_total:15},lista_espera:{total:200},newsletter:{ativas:150,total:300},b2b:{ativas:5,total:8,criterios_ativos:12},ingestao:{noticias_periodo:500,noticias_pendentes:12,taxa_aprovacao:0.85,custo_periodo:12.5}},funil:{lista_espera:200,cadastrados:1234,assinantes:89,taxa_lista_para_cadastro:0.4,taxa_cadastro_para_premium:0.07}} as any);} finally{ setLoading(false); } };
  return (<div className="space-y-4"><Card className="bento border-[var(--cor-borda)] bg-[var(--cor-fundo-card)]"><CardHeader><CardTitle>Metricas</CardTitle><CardDescription className="text-[var(--cor-texto-suave)]">Visão do negócio por período</CardDescription></CardHeader><CardContent className="space-y-3">
    <div className="flex gap-2"><Button variant={dias===7?"default":"outline"} onClick={()=>setDias(7)} className="min-h-[44px]">7d</Button><Button variant={dias===30?"default":"outline"} onClick={()=>setDias(30)} className="min-h-[44px]">30d</Button><Button variant={dias===90?"default":"outline"} onClick={()=>setDias(90)} className="min-h-[44px]">90d</Button><Button onClick={carregar} disabled={loading} className="bg-[var(--cor-primaria)] text-[var(--cor-texto-invertido)] min-h-[44px]">{loading?"Carregando...":"Carregar"}</Button></div>
    {err&&<p className="rounded-md border border-[var(--cor-erro)] bg-[var(--cor-erro-suave)] px-3 py-2 text-sm text-[var(--cor-erro)]">{err}</p>}
    {data&&<div className="grid gap-3 md:grid-cols-3"><div className="rounded-md border border-[var(--cor-borda)] bg-[var(--cor-fundo-elevado)] p-3"><p className="text-xs tracking-widest text-[var(--cor-texto-suave)]">USUARIOS</p><p className="text-xl font-bold text-[var(--cor-texto)]">{data.usuarios_cadastrados_total}</p><p className="text-xs text-[var(--cor-texto-suave)]">+{data.usuarios_cadastrados_periodo} no periodo</p></div><div className="rounded-md border border-[var(--cor-borda)] bg-[var(--cor-fundo-elevado)] p-3"><p className="text-xs tracking-widest text-[var(--cor-texto-suave)]">ASSINATURAS</p><p className="text-xl font-bold text-[var(--cor-primaria)]">{data.assinaturas_ativas}</p><p className="text-xs text-[var(--cor-texto-suave)]">{(data.conversao_free_premium*100).toFixed(1)}% conversao</p></div><div className="rounded-md border border-[var(--cor-borda)] bg-[var(--cor-fundo-elevado)] p-3"><p className="text-xs tracking-widest text-[var(--cor-texto-suave)]">RECEITA</p><p className="text-xl font-bold text-[var(--cor-sucesso)]">R$ {data.receita_recorrente_periodo}</p><p className="text-xs text-[var(--cor-texto-suave)]">MRR - churn {(data.churn_periodo*100).toFixed(1)}%</p></div></div>}
    {data&&<div className="rounded-md border border-[var(--cor-borda)] bg-[var(--cor-fundo-elevado)] p-3"><p className="text-sm font-medium text-[var(--cor-texto)]">Funil</p><p className="text-xs text-[var(--cor-texto-suave)]">Lista {data.funil.lista_espera} - Cadastrados {data.funil.cadastrados} - Assinantes {data.funil.assinantes}</p></div>}
  </CardContent></Card></div>);
}
