# Generated by Django 5.2.17 on 2026-09-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventobusca',
            new_name='feed_evento_query_n_a300f3_idx',
            old_name='feed_evento_query_n_8f7c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='interacaonoticia',
            new_name='feed_intera_entry_t_b14e84_idx',
            old_name='feed_inter_entry__c2c1f9_idx',
        ),
        migrations.RenameIndex(
            model_name='interacaonoticia',
            new_name='feed_intera_entry_t_b6d2e8_idx',
            old_name='feed_inter_entry__9a4b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='interacaonoticia',
            new_name='feed_intera_tipo_0f1868_idx',
            old_name='feed_inter_tipo_6d3a2f_idx',
        ),
    ]
