# Generated by Django 5.2.17 on 2026-09-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_eventosite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventosite',
            new_name='metricas_ev_tipo_0d85e2_idx',
            old_name='metricas_ev_tipo_criado_idx',
        ),
        migrations.RenameIndex(
            model_name='eventosite',
            new_name='metricas_ev_sessao_f1161e_idx',
            old_name='metricas_ev_sessao_criado_idx',
        ),
        migrations.RenameIndex(
            model_name='eventosite',
            new_name='metricas_ev_categor_08e548_idx',
            old_name='metricas_ev_categ_criado_idx',
        ),
    ]
